version: "3.8"

services:

  postgreSQL:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - local_database/database:/var/lib/postgresql/data
